export const pokemoji = [
  { id: 0, char: "-", possible: false, type: 0 },
  {
    id: 1,
    char: "イ゛",
    possible: false,
    dakuten: "゛",
    initchar: "イ",
    type: 1,
  },
  {
    id: 2,
    char: "ウ゛",
    possible: false,
    dakuten: "゛",
    initchar: "ウ",
    type: 1,
  },
  {
    id: 3,
    char: "エ゛",
    possible: false,
    dakuten: "゛",
    initchar: "エ",
    type: 1,
  },
  {
    id: 4,
    char: "オ゛",
    possible: false,
    dakuten: "゛",
    initchar: "オ",
    type: 1,
  },
  { id: 5, char: "ガ", possible: true, dakuten: "゛", initchar: "カ", type: 1 },
  { id: 6, char: "ギ", possible: true, dakuten: "゛", initchar: "キ", type: 1 },
  { id: 7, char: "グ", possible: false, initchar: "ク", type: 1 },
  { id: 8, char: "ゲ", possible: true, dakuten: "゛", initchar: "ケ", type: 1 },
  { id: 9, char: "ゴ", possible: true, dakuten: "゛", initchar: "コ", type: 1 },
  {
    id: 10,
    char: "ザ",
    possible: true,
    dakuten: "゛",
    initchar: "サ",
    type: 1,
  },
  {
    id: 11,
    char: "ジ",
    possible: true,
    dakuten: "゛",
    initchar: "シ",
    type: 1,
  },
  {
    id: 12,
    char: "ズ",
    possible: true,
    dakuten: "゛",
    initchar: "ス",
    type: 1,
  },
  {
    id: 13,
    char: "ゼ",
    possible: true,
    dakuten: "゛",
    initchar: "セ",
    type: 1,
  },
  {
    id: 14,
    char: "ゾ",
    possible: true,
    dakuten: "゛",
    initchar: "ソ",
    type: 1,
  },
  {
    id: 15,
    char: "ダ",
    possible: true,
    dakuten: "゛",
    initchar: "タ",
    type: 1,
  },
  {
    id: 16,
    char: "ヂ",
    possible: true,
    dakuten: "゛",
    initchar: "チ",
    type: 1,
  },
  {
    id: 17,
    char: "ヅ",
    possible: true,
    dakuten: "゛",
    initchar: "ツ",
    type: 1,
  },
  {
    id: 18,
    char: "デ",
    possible: true,
    dakuten: "゛",
    initchar: "テ",
    type: 1,
  },
  {
    id: 19,
    char: "ド",
    possible: true,
    dakuten: "゛",
    initchar: "ト",
    type: 1,
  },
  {
    id: 20,
    char: "ナ゛",
    possible: false,
    dakuten: "゛",
    initchar: "ナ",
    type: 1,
  },
  {
    id: 21,
    char: "ニ゛",
    possible: false,
    dakuten: "゛",
    initchar: "ニ",
    type: 1,
  },
  {
    id: 22,
    char: "ヌ゛",
    possible: false,
    dakuten: "゛",
    initchar: "ヌ",
    type: 1,
  },
  {
    id: 23,
    char: "ネ゛",
    possible: false,
    dakuten: "゛",
    initchar: "ネ",
    type: 1,
  },
  {
    id: 24,
    char: "ノ゛",
    possible: false,
    dakuten: "゛",
    initchar: "ノ",
    type: 1,
  },
  {
    id: 25,
    char: "バ",
    possible: true,
    dakuten: "゛",
    initchar: "ハ",
    type: 1,
  },
  {
    id: 26,
    char: "ビ",
    possible: true,
    dakuten: "゛",
    initchar: "ヒ",
    type: 1,
  },
  {
    id: 27,
    char: "ブ",
    possible: true,
    dakuten: "゛",
    initchar: "フ",
    type: 1,
  },
  {
    id: 28,
    char: "ボ",
    possible: true,
    dakuten: "゛",
    initchar: "ホ",
    type: 1,
  },
  {
    id: 29,
    char: "マ゛",
    possible: false,
    dakuten: "゛",
    initchar: "マ",
    type: 1,
  },
  {
    id: 30,
    char: "ミ゛",
    possible: false,
    dakuten: "゛",
    initchar: "ミ",
    type: 1,
  },
  {
    id: 31,
    char: "ム゛",
    possible: false,
    dakuten: "゛",
    initchar: "ム",
    type: 1,
  },
  {
    id: 32,
    char: "ィ゛",
    possible: false,
    dakuten: "゛",
    initchar: "ィ",
    type: 1,
  },
  {
    id: 33,
    char: "あ゛",
    possible: false,
    dakuten: "゛",
    initchar: "あ",
    type: 2,
  },
  {
    id: 34,
    char: "い゛",
    possible: false,
    dakuten: "゛",
    initchar: "い",
    type: 2,
  },
  {
    id: 35,
    char: "う゛",
    possible: false,
    dakuten: "゛",
    initchar: "う",
    type: 2,
  },
  {
    id: 36,
    char: "え゛",
    possible: false,
    dakuten: "゛",
    initchar: "え",
    type: 2,
  },
  {
    id: 37,
    char: "お゛",
    possible: false,
    dakuten: "゛",
    initchar: "お",
    type: 2,
  },
  {
    id: 38,
    char: "が",
    possible: true,
    dakuten: "゛",
    initchar: "か",
    type: 2,
  },
  {
    id: 39,
    char: "ぎ",
    possible: true,
    dakuten: "゛",
    initchar: "き",
    type: 2,
  },
  {
    id: 40,
    char: "ぐ",
    possible: true,
    dakuten: "゛",
    initchar: "く",
    type: 2,
  },
  {
    id: 41,
    char: "げ",
    possible: true,
    dakuten: "゛",
    initchar: "け",
    type: 2,
  },
  {
    id: 42,
    char: "ご",
    possible: true,
    dakuten: "゛",
    initchar: "こ",
    type: 2,
  },
  {
    id: 43,
    char: "ざ",
    possible: true,
    dakuten: "゛",
    initchar: "さ",
    type: 2,
  },
  {
    id: 44,
    char: "じ",
    possible: true,
    dakuten: "゛",
    initchar: "し",
    type: 2,
  },
  {
    id: 45,
    char: "ず",
    possible: true,
    dakuten: "゛",
    initchar: "す",
    type: 2,
  },
  {
    id: 46,
    char: "ぜ",
    possible: true,
    dakuten: "゛",
    initchar: "せ",
    type: 2,
  },
  {
    id: 47,
    char: "ぞ",
    possible: true,
    dakuten: "゛",
    initchar: "そ",
    type: 2,
  },
  {
    id: 48,
    char: "だ",
    possible: true,
    dakuten: "゛",
    initchar: "た",
    type: 2,
  },
  {
    id: 49,
    char: "ぢ",
    possible: true,
    dakuten: "゛",
    initchar: "ち",
    type: 2,
  },
  {
    id: 50,
    char: "づ",
    possible: true,
    dakuten: "゛",
    initchar: "つ",
    type: 2,
  },
  {
    id: 51,
    char: "で",
    possible: true,
    dakuten: "゛",
    initchar: "て",
    type: 2,
  },
  {
    id: 52,
    char: "ど",
    possible: true,
    dakuten: "゛",
    initchar: "と",
    type: 2,
  },
  {
    id: 53,
    char: "な゛",
    possible: false,
    dakuten: "゛",
    initchar: "な",
    type: 2,
  },
  {
    id: 54,
    char: "に゛",
    possible: false,
    dakuten: "゛",
    initchar: "に",
    type: 2,
  },
  {
    id: 55,
    char: "ぬ゛",
    possible: false,
    dakuten: "゛",
    initchar: "ぬ",
    type: 2,
  },
  {
    id: 56,
    char: "ね゛",
    possible: false,
    dakuten: "゛",
    initchar: "ね",
    type: 2,
  },
  {
    id: 57,
    char: "の゛",
    possible: false,
    dakuten: "゛",
    initchar: "の",
    type: 2,
  },
  {
    id: 58,
    char: "ば",
    possible: true,
    dakuten: "゛",
    initchar: "は",
    type: 2,
  },
  {
    id: 59,
    char: "び",
    possible: true,
    dakuten: "゛",
    initchar: "ひ",
    type: 2,
  },
  {
    id: 60,
    char: "ぶ",
    possible: true,
    dakuten: "゛",
    initchar: "ふ",
    type: 2,
  },
  {
    id: 61,
    char: "ベ",
    possible: true,
    dakuten: "゛",
    initchar: "ヘ",
    type: 2,
  },
  {
    id: 62,
    char: "ぼ",
    possible: true,
    dakuten: "゛",
    initchar: "ほ",
    type: 2,
  },
  {
    id: 63,
    char: "ま゛",
    possible: false,
    dakuten: "゛",
    initchar: "ま",
    type: 2,
  },
  {
    id: 64,
    char: "パ",
    possible: true,
    dakuten: "゜",
    initchar: "ハ",
    type: 1,
  },
  {
    id: 65,
    char: "ピ",
    possible: true,
    dakuten: "゜",
    initchar: "ヒ",
    type: 1,
  },
  {
    id: 66,
    char: "プ",
    possible: true,
    dakuten: "゜",
    initchar: "フ",
    type: 1,
  },
  {
    id: 67,
    char: "ポ",
    possible: true,
    dakuten: "゜",
    initchar: "ホ",
    type: 1,
  },
  {
    id: 68,
    char: "ぱ",
    possible: true,
    dakuten: "゜",
    initchar: "は",
    type: 2,
  },
  {
    id: 69,
    char: "ぴ",
    possible: true,
    dakuten: "゜",
    initchar: "ひ",
    type: 2,
  },
  {
    id: 70,
    char: "ぷ",
    possible: true,
    dakuten: "゜",
    initchar: "ふ",
    type: 2,
  },
  {
    id: 71,
    char: "ペ",
    possible: true,
    dakuten: "゜",
    initchar: "ヘ",
    type: 2,
  },
  {
    id: 72,
    char: "ぽ",
    possible: true,
    dakuten: "゜",
    initchar: "ほ",
    type: 2,
  },
  {
    id: 73,
    char: "ま゜",
    possible: false,
    dakuten: "゜",
    initchar: "ま",
    type: 2,
  },
  {
    id: 74,
    char: "み゜",
    possible: false,
    dakuten: "゜",
    initchar: "み",
    type: 2,
  },
  { id: 75, char: "文字送り", possible: false, type: 0 },
  { id: 76, char: "自動送り", possible: false, type: 0 },
  {
    id: 77,
    char: "も゜",
    possible: false,
    dakuten: "゜",
    initchar: "も",
    type: 2,
  },
  { id: 78, char: "1行改行", possible: false, type: 0 },
  { id: 79, char: "改行", possible: false, type: 0 },
  { id: 80, char: "終", possible: false, type: 0 },
  { id: 81, char: "文字送り", possible: false, type: 0 },
  { id: 82, char: "主人公の名前", possible: false, type: 0 },
  { id: 83, char: "ライバル名前", possible: false, type: 0 },
  { id: 84, char: "0", possible: false, type: 0 },
  { id: 85, char: "文字送り", possible: false, type: 0 },
  { id: 86, char: "……", possible: false, type: 0 },
  { id: 87, char: "無効", possible: false, type: 0 },
  { id: 88, char: "改ページ", possible: false, type: 0 },
  { id: 89, char: "ポケモン1", possible: false, type: 0 },
  { id: 90, char: "ポケモン2", possible: false, type: 0 },
  { id: 91, char: "パソコン", possible: false, type: 0 },
  { id: 92, char: "わざマシン", possible: false, type: 0 },
  { id: 93, char: "トレーナー", possible: false, type: 0 },
  { id: 94, char: "ロケットだん", possible: false, type: 0 },
  { id: 95, char: "、、゜", possible: false, type: 0 },
  { id: 96, char: "A", possible: false, type: 0 },
  { id: 97, char: "B", possible: false, type: 0 },
  { id: 98, char: "] ：| ,", possible: false, type: 0 },
  { id: 99, char: "HPゲージ0/8", possible: false, type: 0 },
  { id: 100, char: "HPゲージ1/8", possible: false, type: 0 },
  { id: 101, char: "HPゲージ2/8", possible: false, type: 0 },
  { id: 102, char: "HPゲージ3/8", possible: false, type: 0 },
  { id: 103, char: "HPゲージ4/8", possible: false, type: 0 },
  { id: 104, char: "HPゲージ5/8", possible: false, type: 0 },
  { id: 105, char: "HPゲージ6/8", possible: false, type: 0 },
  { id: 106, char: "HPゲージ7/8", possible: false, type: 0 },
  { id: 107, char: "HPゲージ8/8", possible: false, type: 0 },
  { id: 108, char: ",", possible: false, type: 0 },
  { id: 109, char: ",||", possible: false, type: 0 },
  { id: 110, char: ":L", possible: false, type: 0 },
  { id: 111, char: "左とんがり", possible: false, type: 0 },
  { id: 112, char: "ど", possible: false, type: 0 },
  { id: 113, char: "H1", possible: false, type: 0 },
  { id: 114, char: "『", possible: false, type: 0 },
  { id: 115, char: "ID", possible: false, type: 0 },
  { id: 116, char: "No", possible: false, type: 0 },
  { id: 117, char: "…", possible: false, type: 0 },
  { id: 118, char: "━", possible: false, type: 0 },
  { id: 119, char: "￣", possible: false, type: 0 },
  { id: 120, char: "右とんがり", possible: false, type: 0 },
  { id: 121, char: "┏", possible: false, type: 0 },
  { id: 122, char: "＝", possible: false, type: 0 },
  { id: 123, char: "┓", possible: false, type: 0 },
  { id: 124, char: "||", possible: false, type: 0 },
  { id: 125, char: "┗", possible: false, type: 0 },
  { id: 126, char: "┛", possible: false, type: 0 },
  { id: 127, char: "　", possible: true, type: 0 },
  { id: 128, char: "ア", possible: true, type: 1 },
  { id: 129, char: "イ", possible: true, type: 1 },
  { id: 130, char: "ウ", possible: true, type: 1 },
  { id: 131, char: "エ", possible: true, type: 1 },
  { id: 132, char: "オ", possible: true, type: 1 },
  { id: 133, char: "カ", possible: true, type: 1 },
  { id: 134, char: "キ", possible: true, type: 1 },
  { id: 135, char: "ク", possible: true, type: 1 },
  { id: 136, char: "ケ", possible: true, type: 1 },
  { id: 137, char: "コ", possible: true, type: 1 },
  { id: 138, char: "サ", possible: true, type: 1 },
  { id: 139, char: "シ", possible: true, type: 1 },
  { id: 140, char: "ス", possible: true, type: 1 },
  { id: 141, char: "セ", possible: true, type: 1 },
  { id: 142, char: "ソ", possible: true, type: 1 },
  { id: 143, char: "タ", possible: true, type: 1 },
  { id: 144, char: "チ", possible: true, type: 1 },
  { id: 145, char: "ツ", possible: true, type: 1 },
  { id: 146, char: "テ", possible: true, type: 1 },
  { id: 147, char: "ト", possible: true, type: 1 },
  { id: 148, char: "ナ", possible: true, type: 1 },
  { id: 149, char: "ニ", possible: true, type: 1 },
  { id: 150, char: "ヌ", possible: true, type: 1 },
  { id: 151, char: "ネ", possible: true, type: 1 },
  { id: 152, char: "ノ", possible: true, type: 1 },
  { id: 153, char: "ハ", possible: true, type: 1 },
  { id: 154, char: "ヒ", possible: true, type: 1 },
  { id: 155, char: "フ", possible: true, type: 1 },
  { id: 156, char: "ホ", possible: true, type: 1 },
  { id: 157, char: "マ", possible: true, type: 1 },
  { id: 158, char: "ミ", possible: true, type: 1 },
  { id: 159, char: "ム", possible: true, type: 1 },
  { id: 160, char: "メ", possible: true, type: 1 },
  { id: 161, char: "モ", possible: true, type: 1 },
  { id: 162, char: "ヤ", possible: true, type: 1 },
  { id: 163, char: "ユ", possible: true, type: 1 },
  { id: 164, char: "ヨ", possible: true, type: 1 },
  { id: 165, char: "ラ", possible: true, type: 1 },
  { id: 166, char: "ル", possible: true, type: 1 },
  { id: 167, char: "レ", possible: true, type: 1 },
  { id: 168, char: "ロ", possible: true, type: 1 },
  { id: 169, char: "ワ", possible: true, type: 1 },
  { id: 170, char: "ヲ", possible: false, type: 1 },
  { id: 171, char: "ン", possible: true, type: 1 },
  { id: 172, char: "ッ", possible: true, type: 1 },
  { id: 173, char: "ャ", possible: true, type: 1 },
  { id: 174, char: "ュ", possible: true, type: 1 },
  { id: 175, char: "ョ", possible: true, type: 1 },
  { id: 176, char: "ィ", possible: false, type: 1 },
  { id: 177, char: "あ", possible: true, type: 2 },
  { id: 178, char: "い", possible: true, type: 2 },
  { id: 179, char: "う", possible: true, type: 2 },
  { id: 180, char: "え", possible: true, type: 2 },
  { id: 181, char: "お", possible: true, type: 2 },
  { id: 182, char: "か", possible: true, type: 2 },
  { id: 183, char: "き", possible: true, type: 2 },
  { id: 184, char: "く", possible: true, type: 2 },
  { id: 185, char: "け", possible: true, type: 2 },
  { id: 186, char: "こ", possible: true, type: 2 },
  { id: 187, char: "さ", possible: true, type: 2 },
  { id: 188, char: "し", possible: true, type: 2 },
  { id: 189, char: "す", possible: true, type: 2 },
  { id: 190, char: "せ", possible: true, type: 2 },
  { id: 191, char: "そ", possible: true, type: 2 },
  { id: 192, char: "た", possible: true, type: 2 },
  { id: 193, char: "ち", possible: true, type: 2 },
  { id: 194, char: "つ", possible: true, type: 2 },
  { id: 195, char: "て", possible: true, type: 2 },
  { id: 196, char: "と", possible: true, type: 2 },
  { id: 197, char: "な", possible: true, type: 2 },
  { id: 198, char: "に", possible: true, type: 2 },
  { id: 199, char: "ぬ", possible: true, type: 2 },
  { id: 200, char: "ね", possible: true, type: 2 },
  { id: 201, char: "の", possible: true, type: 2 },
  { id: 202, char: "は", possible: true, type: 2 },
  { id: 203, char: "ひ", possible: true, type: 2 },
  { id: 204, char: "ふ", possible: true, type: 2 },
  { id: 205, char: "ヘ", possible: true, type: 2 },
  { id: 206, char: "ほ", possible: true, type: 2 },
  { id: 207, char: "ま", possible: true, type: 2 },
  { id: 208, char: "み", possible: true, type: 2 },
  { id: 209, char: "む", possible: true, type: 2 },
  { id: 210, char: "め", possible: true, type: 2 },
  { id: 211, char: "も", possible: true, type: 2 },
  { id: 212, char: "や", possible: true, type: 2 },
  { id: 213, char: "ゆ", possible: true, type: 2 },
  { id: 214, char: "よ", possible: true, type: 2 },
  { id: 215, char: "ら", possible: true, type: 2 },
  { id: 216, char: "リ", possible: true, type: 2 },
  { id: 217, char: "る", possible: true, type: 2 },
  { id: 218, char: "れ", possible: true, type: 2 },
  { id: 219, char: "ろ", possible: true, type: 2 },
  { id: 220, char: "わ", possible: true, type: 2 },
  { id: 221, char: "を", possible: false, type: 2 },
  { id: 222, char: "ん", possible: true, type: 2 },
  { id: 223, char: "っ", possible: true, type: 2 },
  { id: 224, char: "ゃ", possible: true, type: 2 },
  { id: 225, char: "ゅ", possible: true, type: 2 },
  { id: 226, char: "ょ", possible: true, type: 2 },
  { id: 227, char: "ー", possible: true, type: 0 },
  { id: 228, char: "ﾟ", possible: false, type: 0 },
  { id: 229, char: "゛", possible: false, type: 0 },
  { id: 230, char: "？", possible: false, type: 0 },
  { id: 231, char: "！", possible: false, type: 0 },
  { id: 232, char: "。", possible: false, type: 0 },
  { id: 233, char: "ァ", possible: false, type: 1 },
  { id: 234, char: "ゥ", possible: false, type: 1 },
  { id: 235, char: "ェ", possible: false, type: 1 },
  { id: 236, char: "▷", possible: false, type: 0 },
  { id: 237, char: "▶", possible: false, type: 0 },
  { id: 238, char: "▼", possible: false, type: 0 },
  { id: 239, char: "♂", possible: false, type: 0 },
  { id: 240, char: "円", possible: false, type: 0 },
  { id: 241, char: "×", possible: false, type: 0 },
  { id: 242, char: "．", possible: false, type: 0 },
  { id: 243, char: "／", possible: false, type: 0 },
  { id: 244, char: "ォ", possible: false, type: 1 },
  { id: 245, char: "♀", possible: false, type: 0 },
  { id: 246, char: "0", possible: false, type: 0 },
  { id: 247, char: "1", possible: false, type: 0 },
  { id: 248, char: "2", possible: false, type: 0 },
  { id: 249, char: "3", possible: false, type: 0 },
  { id: 250, char: "4", possible: false, type: 0 },
  { id: 251, char: "5", possible: false, type: 0 },
  { id: 252, char: "6", possible: false, type: 0 },
  { id: 253, char: "7", possible: false, type: 0 },
  { id: 254, char: "8", possible: false, type: 0 },
  { id: 255, char: "9", possible: false, type: 0 },
];

export const pokemojiMap = pokemoji.map((p) => {
  return { [p.char]: p };
});
