import type { Metadata } from "next";
import { Geist, Geist_Mono, Kiwi_Maru, Noto_Sans_JP } from "next/font/google";
import "./globals.css";
import ThemeProviderWrapper from "./components/common/ThemeProviderWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const noteSansJp = Noto_Sans_JP({
  variable: "--font-noto-sans-jp",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const kiwiMaru = Kiwi_Maru({
  variable: "--font-kiwi-maru",
  subsets: ["latin"],
  weight: "300",
});

export const metadata: Metadata = {
  title: "プログラム集",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ThemeProviderWrapper>
      <html lang="ja">
        <body
          className={`${geistSans.variable} ${geistMono.variable} ${kiwiMaru.variable} ${noteSansJp.variable} antialiased`}
        >
          {children}
        </body>
      </html>
    </ThemeProviderWrapper>
  );
}
